apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        # include /etc/nginx/conf.d/*.conf;
        server {
            listen 8080;
            server_name shop.lengirt.ru;

            root /usr/share/nginx/html;
            index index.html;

            location / {
                try_files $uri $uri/ /index.html;
            }

            location = /healthz {
                access_log off;
                log_not_found off;
                return 200 'ok';
                add_header Content-Type text/plain;
            }

            location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|eot|otf)$ {
                expires 1y;
                access_log off;
                add_header Cache-Control "public, immutable";
            }

            location ~ /\. {
                deny all;
            }
        }
    }

