apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-svc
spec:
  type: ClusterIP 
  selector:
    app: {{ $.Chart.Name }}
  ports:
    - port: 80 
      name: http
      targetPort: 8080 
    - port: 443 
      name: https
      targetPort: 8080